### ISSUE TITLE
How to undo/uninstall this script. 

### ISSUE THREAD

**Issue by zolrac2k** [NikushaKalatozi/MacOS-Big-Sur-Sharing-Host-VPN-with-Guest#2]
Hello, I ran your script as I had the same issues, unable to get my Windows VM to share the same VPN connection as on my host (MacOS 11.4). 

However, the script is not working for me on my VM, even though I made sure to run it on my MacOS host. 

Do you have an uninstall/undo script to remove the changes made as now with the script used it doesn't allow me to even get out onto the Internet from my Windows VM were prior to using your script, I was still able to get onto the Internet from the Windows VM, I just wasn't able to share the VPN connection that my MacOS host was connected to. 

Any help would be greatly appreciated.

**Comment by NikushaKalatozi** [comment]
@zolrac2k Hi, do you use the OpenVPN config file to run VPN? I think if you use the OpenVPN config file you should not face any issues.

**Comment by Darkcast** [comment]
I was thinking the same thing, like if I use a vpn application on my mac and I use this config will it revertback after I turnoff my vpn or do I have to manully remove the firewall rules ?
