### ISSUE TITLE
Discards network rules.

### ISSUE THREAD

**Issue by lacraig2** [NikushaKalatozi/MacOS-Big-Sur-Sharing-Host-VPN-with-Guest#4]
So this line takes accounting of the current set of rules:
https://github.com/NikushaKalatozi/MacOS-Big-Sur-Sharing-Host-VPN-with-Guest/blob/3e326c85f1bf4c3575afe5ef96f8f300ac6868e5/vpn_tunnel.sh#L20

But when adding here the `>` operator discards the earlier results:
https://github.com/NikushaKalatozi/MacOS-Big-Sur-Sharing-Host-VPN-with-Guest/blob/3e326c85f1bf4c3575afe5ef96f8f300ac6868e5/vpn_tunnel.sh#L23

I don't know enough about `pfctl` to know if we just want the new rule or if the operator above should just be `>>`, but I figured I'd ask.

**Comment by NikushaKalatozi** [comment]
This is done due to not creating files locally on disk.
